### ISSUE TITLE
Can I train this modle with my own data in coco format?

### ISSUE THREAD

**Issue by Bluswy** [yhenon/pytorch-retinanet#111]
Can I train this modle with my own data in coco format?

**Comment by Summar-sky** [comment]
Of course, I am doing.

**Comment by agoel15006** [comment]
@Summar-sky my own data is having 8 classes but the pretrained model is on 80 classes of standard MS COCO dataset. So, where should I make the changes in num_classes? I tried to change but get the following error.

Error:
Traceback (most recent call last):
  File "coco_validation.py", line 44, in <module>
    main()
  File "coco_validation.py", line 33, in main
    retinanet.load_state_dict(torch.load(parser.model_path))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResNet:
	size mismatch for classificationModel.output.weight: copying a param with shape torch.Size([720, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([72, 256, 3, 3]).
	size mismatch for classificationModel.output.bias: copying a param with shape torch.Size([720]) from checkpoint, the shape in current model is torch.Size([72]).

**Comment by Summar-sky** [comment]
@agoel15006  I think you need to modify the data set path in your project. I hope my advice will help you.

**Comment by agoel15006** [comment]
@Summar-sky the dataset path is already changed and the code is also pointing to new annotations and dataset but since new dataset contains 8 classes, the last layer classification model is throwing error as it is trained on 80 classes.

**Comment by rvandeghen** [comment]
In the dataloader file in the CocoDataset class there is a function `num_classes` which return 80 so you can change here. Or in the instantiation of the classification network you can change the num_class attribute. Hope this will help you

**Comment by yhenon** [comment]
If your dataset is compatible with the coco python API tool it should work, although I have not tested this. As @rvandeghen mentioned, you will also need to hard code in the number of classes.

**Comment by nikeshdevkota** [comment]
@yhenon I tried to use the coco-validation tool for my own custom dataset having 1 class. But, I get 0.000 values for all average precision and recall. Can you provide some information on how to generate the evaluation metrics correctly? I am using the coco validation to get AP and AR @[ IoU=0.50:0.95] mainly at the max detection threshold of 100. Also, if I use different-sized objects, I want to calculate AP based on the object size. 

I have already loaded the data from the data loader for my custom data and have a trained model as well. 

When I use the csv_validation.py file and calculate the AP, I get the desired outcomes. The IOU threshold used in the cvs_validation is 0.5 and the score threshold is 0.05.

![Capture1](https://user-images.githubusercontent.com/45029614/208587682-b7e44f16-e19f-45e6-a874-ef85df3202d5.PNG)

When I use the coco_validation.py file and calculate the AP, I don't get the desired outcomes. The -1 in medium and large targets is because I don't have objects of those sizes.

![Capture](https://user-images.githubusercontent.com/45029614/208585992-196e419b-842f-446f-8e32-ae720b333a2a.PNG)
