### ISSUE TITLE
Why did you freeze the BN when training ?

### ISSUE THREAD

**Issue by renmengyuan** [yhenon/pytorch-retinanet#151]
retinanet.train()
    retinanet.module.freeze_bn()

**Comment by bonlime** [comment]
It's a common practice to freeze BN while training object detection models. This is done because you usually start from some Imagenet pre-trained weights which were trained with large BS (like 256 or larger) while in object detection BS is much smaller. You don't want to ruin good pretrained statistics so freezing BN is a good idea
