### ISSUE TITLE
Why do we use AspectRatioBasedSampler?

### ISSUE THREAD

**Issue by JoshVarty** [yhenon/pytorch-retinanet#89]
I'm curious about the reason for using `AspectRatioBasedSampler` to create batches during training. Is there an advantage to training on images of similar aspect ratios?

**Comment by gunshi** [comment]
Yes, because we'll be creating batches of these images, and since each image has varying sizes, we want to have mostly similar images in a batch so that they have to undergo minimal padding to make them the same size (we need to same eventually the same size for all images in a batch because of how anchors are computed)
